### ISSUE TITLE
Use the init function on the @fullstory/browser SDK

### ISSUE THREAD

**Issue by patrick-fs** [segmentio/action-destinations#256]
Hello,

I noticed that there is a bespoke wrapper for FullStory's snippet in https://github.com/segmentio/action-destinations/blob/main/packages/browser-destinations/src/destinations/fullstory/init-script.ts

This represents a separate copy of the snippet that will need to be maintained. Rather than maintain a separate copy of the snippet use

```
import * as FullStory from '@fullstory/browser'

initialize: async ({ settings }, dependencies) => {
    FullStory.init(settings)
    // I haven't yet taken a dive into the action destination interface to understand the return value and wait condition here, but including for consitency
    await dependencies.resolveWhen(() => Object.prototype.hasOwnProperty.call(window, 'FS'), 100)
    return FullStory
  }

```

in https://github.com/segmentio/action-destinations/blob/main/packages/browser-destinations/src/destinations/fullstory/index.ts

The `@fullstory/browser` SDK ([docs](https://www.npmjs.com/package/@fullstory/browser)) will have the latest version of our snippet and thus we won't have to maintain it in multiple places for the browser action destination.

WDYT?

**Comment by danieljackins** [comment]
@patrick-fs i'll look at this this week 👍

**Comment by danieljackins** [comment]
Hey @patrick-fs, after chatting on zoom with FullStory we thought it might make sense to do this change after you guys push the updated version to NPM that has setVars available. Does that work?

**Comment by patrick-fs** [comment]
Hey @danieljackins that sounds good to me. Thank you.

**Comment by pooyaj** [comment]
Tracking this internally using `LIBWEB-1013`

**Comment by joshrynneFS** [comment]
Hi @danieljackins - our npm package was updated (https://www.npmjs.com/package/@fullstory/browser/v/1.5.0) to include the setVars function.

**Comment by danieljackins** [comment]
Hi! I believe we switched to the npm package here https://github.com/segmentio/action-destinations/pull/430
