### ISSUE TITLE
Publish CI workflow fails on PRs from forks

### ISSUE THREAD

**Issue by daltonscharff** [segmentio/action-destinations#295]
https://github.com/segmentio/action-destinations/runs/4012357657?check_suite_focus=true

```
Determining the checkout info
  /usr/bin/git branch --list --remote origin/akim-mp-fixes-again
  /usr/bin/git tag --list akim-mp-fixes-again
  Error: A branch or tag with the name 'akim-mp-fixes-again' could not be found
```

It appears that the checkout step fails when attempting to create a canary package from a forked repo. Perhaps supplying the entire repo URL in the `ref` variable of the checkout step will fix this issue.

https://github.com/segmentio/action-destinations/blob/881014ceeb3a7432c22224116dfcf3485044d0e2/.github/workflows/publish.yml#L63

[similar issue](https://github.com/actions/checkout/issues/24)

**Comment by mericsson** [comment]
closing as we are no longer using the publish workflows
