### ISSUE TITLE
git precommit hook incompatible with gitleaks 8

### ISSUE THREAD

**Issue by dhull** [segmentio/action-destinations#369]
`lint-staged.config.js` runs gitleaks, which causes an error with gitleaks 8.

```
✖ gitleaks --repo-url=.git -v --additional-config=.husky/gitleaks-rules.toml --unstaged --branch=friendbuy-cloud-destination
:
Error: unknown flag: --repo-url
Usage:
  gitleaks [command]
```

It looks like the `--repo-url` etc command-line options were removed in [gitleaks 8.0.0](https://github.com/zricethezav/gitleaks/releases/tag/v8.0.0), which was released Nov 22. The now-unused command-line options were ignored with an error message until gitleaks 8.0.5, when they became a fatal error.

**Comment by mericsson** [comment]
@dhull thanks for reporting! We will take a look. Tracking internally here https://segment.atlassian.net/browse/BE-480
