### ISSUE TITLE
crypto.getRandomValues() not supported preventing end-to-end testing

### ISSUE THREAD

**Issue by bgila** [segmentio/action-destinations#372]
Sprig's SDK sometimes invokes `uuid.v4()` for id generation, and for some reason this doesn't seem to work in the yarn testing suite -- I get this error initializing our SDK: `Error: crypto.getRandomValues() not supported. See https://github.com/uuidjs/uuid#getrandomvalues-not-supported`

Continuing to look into it, and I'll add the PR to this issue, but I wanted to flag in case this has been seen before.

**Comment by mshwery** [comment]
Looks like jsdom doesn't include web crypto ootb. https://github.com/jsdom/jsdom/issues/1612

you could try adding this to the setup file to support it (as suggested in the issue).

**Comment by bgila** [comment]
thanks for the pointer, i'll try it out and send an update when i have it!

**Comment by bgila** [comment]
thanks for the help, I was able to fix it by adding a workaround to the setup file as you suggested! https://github.com/segmentio/action-destinations/pull/373/commits/e56e156bae1abf2da84df471ab5d46db9f550f18
