### ISSUE TITLE
Loops Destination still showing deleted action

### ISSUE THREAD

**Issue by tcgilbert** [segmentio/action-destinations#867]
20 days ago, [a pull request](https://github.com/segmentio/action-destinations/pull/832) was merged for the Loops destination that removed a previous action `createContact` and replaced it with a new one `createOrUpdateContact`. 

![Screen Shot 2022-11-10 at 5 42 05 PM](https://user-images.githubusercontent.com/64277654/201221616-3d7c48b4-4671-41bd-b59f-e2e6af3b8f2e.png)

The new action was added successfully, however in the Segment UI there is still the ability to select the `createContact` action.  

![Screen Shot 2022-11-10 at 5 44 14 PM](https://user-images.githubusercontent.com/64277654/201221692-99db45fb-ce29-40ae-bbd5-b740be4ff810.png)

The ask here is to remove the old `createContact` action.

**Comment by NolanChan** [comment]
Confirmed deleted!

<img width="794" alt="Screen Shot 2022-11-17 at 10 53 34 AM" src="https://user-images.githubusercontent.com/1487616/202533459-a49276d8-8873-4d22-9469-fb16c97c0bc2.png">
