### ISSUE TITLE
Local End-to-end Testing - problem appears when changing the port

### ISSUE THREAD

**Issue by weronika-kurczyna** [segmentio/action-destinations#951]
Hi,
Based on the information from this documentation: [Action destinations testing](https://github.com/segmentio/action-destinations/blob/main/docs/testing.md#local-end-to-end-testing),
I tried changing the `port` to other than `3000` (e.g. `9000`). 
But after picking another port, the **Action Tester** doesn't fetch data and an error is thrown in the console regarding refused connection to `localhost:3000 - manifest.json`. It happens in each destination. 
We tried to debug it and find the solution on our own, also changing `DEFAULT_PORT` in `serve.ts` and `server.ts` files, but it did not solve the problem. It looks like at some point the correct port is not assigned. Do you perhaps know the cause of this issue? Thank you in advance.

<img width="962" alt="Screenshot at Dec 29 16-15-52" src="https://user-images.githubusercontent.com/117282008/210342359-1d8d5327-ce96-4706-9f31-7282d9783bf3.png">

**Comment by dlasky** [comment]
Hello, the UI for action tester doesn't currently support changing the port. The port can only be modified (for security reasons) on your local server for manual testing with cURL, postman, etc.
